# Site settings
name: jibun sagashi
title: 自分探し
# email: your-email@domain.com
description: "OSSで社会貢献"
baseurl: "/jibun-sagashi/"
url: "https://syugyo.github.io"

# Build settings
markdown: kramdown
permalinks: pretty

