# Site settings
name: jibun sagashi
title: 自分探し
# email: your-email@domain.com
description: "旅に出ます"
baseurl: "/jibun-sagashi"
url: "http://syugyo.github.io"

# Build settings
markdown: kramdown
permalinks: pretty

